---
name: haxe-language-server
description: Language Server Protocol implementation for the Haxe language.
homepage: https://github.com/vshaxe/haxe-language-server
licenses:
  - MIT
languages:
  - Haxe
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/vshaxe/haxe-language-server@62040daf543c234ffbff4077f7ab4024b32510de
  build:
    run: |
      npm install
      npm exec -- lix run vshaxe-build -t language-server
      npm install --production

bin:
  haxe-language-server: node:bin/server.js
